spring:
  profiles: 
       active: 
       -dev
---
spring:
  profiles: dev
  application:
       name: micservicecloud-config-wj-dev
---
spring:
   profiles: test
   application:
        name: micservicecloud-config-wj-test
