spring:
   profiles:
        active:
         -dev
---
server:
    port:  7001 #注册中心占用7001端口

spring: 
    profiles: dev
    application:
           name: micrservicecloud-config-eureka-client

eureka:
  instance:
    hostname:  eureka7001.com
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不是要求检索服务
    service-url:
         defaultZone: http://eureka7001.com:7001/eureka/ #集群
---
server:
    port:  7001#注册中心占用7001端口

spring: 
    profiles: test
    application:
           name: micrservicecloud-config-eureka-client

eureka:
  instance:
    hostname:  eureka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不是要求检索服务
    service-url:
         defaultZone: http://eureka7001.com:7001/eureka/ #集群