spring:
   profiles:
       active:
       -dev
---
server:
  port: 8001

spring:
   profiles: dev
   application:
     name: microservicecloud-dept
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: org.gjt.mm.mysql.Driver
     url: jdbc:mysql://localhost:3306/cloudDB01
     username: root
     password: 520WANGjian
     dbcp2:
        min-idle: 5 #数据库连接池的最小维持连接数
        initial-size: 5  #初始化连接数
        max-total: 5 #最大连接数
        max-wait-millis: 200 #等待连接获取的最大超时间
mybatis:
    type-aliases-package: com.wj.springcloud.entity   #所有Entity别名类所在包
    mapper-locations: classpath:mybatis/mapper/*.xml   #mapper映射文件

eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: micrservicecloud-dept8001
    prefer-ip-address: true
info:
  app.name: wj-micservicecloud
  company.name: www.wj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
   profiles: test
   application:
     name: microservicecloud-dept
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: org.gjt.mm.mysql.Driver
     url: jdbc:mysql://localhost:3306/cloudDB02
     username: root
     password: 520WANGjian
     dbcp2:
        min-idle: 5 #数据库连接池的最小维持连接数
        initial-size: 5  #初始化连接数
        max-total: 5 #最大连接数
        max-wait-millis: 200 #等待连接获取的最大超时间
mybatis:
    type-aliases-package: com.wj.springcloud.entity   #所有Entity别名类所在包
    mapper-locations: classpath:mybatis/mapper/*.xml   #mapper映射文件

eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: micrservicecloud-dept8001
    prefer-ip-address: true
info:
  app.name: wj-micservicecloud
  company.name: www.wj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$